### ISSUE TITLE
 Parameterized Reports

### ISSUE THREAD

**Issue by bowerth** [petebaker/r-makefile-definitions#2]
Hello everyone,
I am trying to generate flavors of the same report. I am using the `params` parameter of `rmarkdown::render()` together with target-specific variables in GNU MAKE. I came up with the following solution that isn't very elegant. It creates a physical clone each time the "master" input file gets modified (`report_params.Rmd`)

Makefile

```make
report_params.md: ${@:.md=.Rmd}

report_params_2.Rmd: report_params.Rmd
	cp report_params.Rmd report_params_2.Rmd

report_params_2.md: PARAMS=list(value_1 = \"a\", value_2 = \"b\")
report_params_2.md: ${@:.md=.Rmd}
```

r-rules.mk:

```make
%.md: %.Rmd
	${RSCRIPT} ${RSCRIPT_OPTS} -e "library(rmarkdown);render(\"${@:.md=.Rmd}\", md_document${RMARKDOWN_MD_OPTS}, params = ${PARAMS})"
```
If you have a better idea how this can be achieved using GNU MAKE, I am all ears!

**Comment by petebaker** [comment]
Hi bowerth

Firstly, my sincere apologies for not responding quickly but my workload has been out of control for the last couple of months. I'm happy to say the work situation has got a lot better the last couple of days

My main comment is that there are many ways to achieve this, with or without using params to rmarkdown::render. For instance, you could just set the parameters either in the Makefile or outside of  the Makefile using standard rules in your Makefile like like

```make
include ~/lib/r-rules.mk
VALUE_1=a
VALUE_2=b
myFile.pdf: myFile.Rmd
```

and in your Rmd file have an R code chunk that gets the values of your environmental variables and overwrites the parameters set in your yaml header if necessary, assuming you have set value_1 and value_2, then with something like

```r
VALUE_1 <- Sys.getenv("VALUE_1")
if (VALUE_1=="") value_1 <- VALUE_1 else value_1 <- params$value_1
```
and the same for value_2. That way you don't have to play around with the params in Make  but it really depends on what you want to do. For instance, with this setup then you can also set the values on the fly with something like

```bash
VALUE_1=c VALUE_2=d make myFile.pdf
```
The same thing may work if you want to produce an .md file but once again it really depends on exactly what you are trying to achieve. For instance, you may want several  output formats from one .md file but you can also do this with render. Naturally, it is also a bit easier to see what you want to do if you had a minimal reproducible example for experimenting

Regards
Peter

**Comment by bowerth** [comment]
Hello Peter,

Many thanks for taking the time to look into this.

Assuming I have a `minimal.Rmd` file:

```
---
title: MAKE Params
params:
  VALUE_1: a
  VALUE_2: b
---

` ``{r code}
print(params$VALUE_1)
print(params$VALUE_2)
` ``
```

and want to use this `minimal.Rmd` file to generate three versions of the same report - one with the default parameters and two "flavors" with modified parameters

```
rmarkdown::render("minimal.Rmd")

rmarkdown::render("minimal.Rmd",
                  output_file = "minimal-2.html",
                  params = list(VALUE_1 = "aa"))

rmarkdown::render("minimal.Rmd",
                  output_file = "minimal-3.html",
                  params = list(VALUE_2 = "bb"))
```

I am looking for an elegant way to cover this sort of "flavoring" based on a single Rmd file using the r-makefile-definitions.

Your approach suggests the creation of a new `Makefile` for each flavor or a separate call to `make` for each flavor.

**Comment by petebaker** [comment]
Hi bowerth

I wasn't suggesting different Makefiles but simply different rules within the same Makefile. 

Thanks for the minimal example which makes things clearer. 

For some time I have thought I should make the rules more general and your suggestion about passing parameters is a very good idea. Basically, I would suggest not actually making minimal.Rmd but never making it because then it will always need to be made even if it is only a phantom (.PHONY) output file. That way we can use the same .Rmd file without too much work. May I suggest that it would be easier to create minimal-1.html, minimal-2.html, minimal-3.html etc

If you think this is useful then I'm very happy to update all the relevant rules in 'r-rules.mk' because that would make the rules for markdown etc much more flexible.

Regards
Peter

You may need to change the MAKE variable (eg to 'gmake' for macOS) but my suggested Makefile with updated rule is

```make
## File: Makefile

MAKE=/usr/bin/make

.PHONY: all
all: minimal-1.html minimal-2.html minimal-3.html

include ~/lib/r-rules.mk

## what if we just use a new rule - good idea to add flexibility so add in extras!!

## redefine pattern rule -----------------------------------------------------------------

RMARKDOWN_HTML_EXTRAS=
%.html: %.Rmd
	${RSCRIPT} ${RSCRIPT_OPTS} -e "library(rmarkdown);render(\"${@:.html=.Rmd}\", html_document${RMARKDOWN_HTML_OPTS} ${RMARKDOWN_HTML_EXTRAS})"

## define different rules for different output files ------------------------------------

minimal-1.html: minimal.Rmd
	${MAKE} -e RMARKDOWN_HTML_EXTRAS=", output_file='minimal-1.html'" minimal.html

minimal-2.html: minimal.Rmd
	${MAKE} -e RMARKDOWN_HTML_EXTRAS=", params=list(VALUE_1='aa'), output_file='minimal-2.html'" minimal.html

minimal-3.html: minimal.Rmd
	${MAKE} -e RMARKDOWN_HTML_EXTRAS=", params=list(VALUE_2='bb'), output_file='minimal-3.html'" minimal.html
```

**Comment by bowerth** [comment]
Many thanks, this is already much better than my own solution. I will include in my r-rules.mk and test if it is workable.
